let
    // 1. Load the CSV file with proper delimiter and encoding
    Source = Csv.Document(File.Contents("C:\example_file_expanded.csv"), [Delimiter=";", Columns=102, Encoding=65001, QuoteStyle=QuoteStyle.None]),
    
    // 2. Use the first row as headers
    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    
    // 3. Keep 'id' and 'data' columns, unpivot all product-related columns
    #"Unpivoted Other Columns" = Table.UnpivotOtherColumns(#"Promoted Headers", {"id", "data"}, "Attribute", "Value"),
    
    // 4. Filter out rows where Value is null or empty (this removes empty product slots)
    #"Filtered Empty Values" = Table.SelectRows(#"Unpivoted Other Columns", each [Value] <> null and [Value] <> ""),
    
    // 5. Split the "Attribute" column into attribute type and product number
    // Using a more robust regex-based approach
    #"Added Custom Column" = Table.AddColumn(#"Filtered Empty Values", "AttributeType", each 
        let
            attr = [Attribute],
            // Extract everything except the trailing digits
            attrType = Text.BeforeDelimiter(attr, Text.End(attr, Text.Length(attr) - Text.Length(Text.TrimEnd(attr, {"0".."9"}))))
        in
            if Text.Length(Text.TrimEnd(attr, {"0".."9"})) > 0 then Text.TrimEnd(attr, {"0".."9"}) else attr
    ),
    
    #"Added Product Index" = Table.AddColumn(#"Added Custom Column", "ProductIndex", each 
        let
            attr = [Attribute],
            // Extract trailing digits
            digits = Text.End(attr, Text.Length(attr) - Text.Length(Text.TrimEnd(attr, {"0".."9"})))
        in
            if digits <> "" then Number.FromText(digits) else 1
    ),
    
    // 6. Remove the original Attribute column
    #"Removed Attribute Column" = Table.RemoveColumns(#"Added Product Index", {"Attribute"}),
    
    // 7. Pivot the AttributeType to create columns for nazwa, ean, sku, ilosc, zdjecie
    #"Pivoted Column" = Table.Pivot(#"Removed Attribute Column", List.Distinct(#"Removed Attribute Column"[AttributeType]), "AttributeType", "Value"),
    
    // 8. Filter out rows where nazwa is empty (incomplete products)
    #"Filtered Complete Products" = Table.SelectRows(#"Pivoted Column", each [nazwa] <> null and [nazwa] <> ""),
    
    // 9. Set proper data types
    #"Changed Type" = Table.TransformColumnTypes(#"Filtered Complete Products",{
        {"id", Int64.Type}, 
        {"data", type text}, 
        {"ProductIndex", Int64.Type}, 
        {"nazwa", type text}, 
        {"ean", type text}, 
        {"sku", type text}, 
        {"ilosc", Int64.Type}, 
        {"zdjecie", type text}
    })
in
    #"Changed Type"
